Collect Scroll event
norux/smart-analytics pull request #13
Opened 2018-09-29 17:14 UTC by LeeSangJun

스크롤 이벤트 수집

2018-09-30 14:05 UTC, hyoj approved these changes

2018-09-30 14:08 UTC, hyoj reviewed
커밋 메시지 제목 행 첫 글자는 대문자로 😃

2018-10-01 01:17 UTC, norux requested changes

2018-10-01 01:17 UTC, norux commented on src/collector/events/scroll.js
> +    this.on('scroll', e => this.scroll(e))
오메 이렇게하면 스크롤이벤트 어마어마할텐데.. 아주 짧게, 예를 들면 `10ms` 라도 쓰로틀링을 넣는건 어떱니까? 
lodash에 간단하게 이용할 수 있는 함수가 구현되어 있습니다.

[lodash:throttle()](https://lodash.com/docs/4.17.10#throttle)

2018-10-04 02:01 UTC, norux approved these changes

2018-10-04 16:53 UTC, merged